services:
  web:
    image: pronunciation-app-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev

  cron:
    image: pronunciation-app-cron-dev
    build:
      context: .
      dockerfile: Dockerfile.cron
