services:
  web:
    image: euanoturner/pronunciation-app:${IMAGE_TAG}
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - USER_MANAGER_SECRET=${USER_MANAGER_SECRET}
      - MODEL_API_URL=${MODEL_API_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
    depends_on:
      - db
      - redis
    restart: unless-stopped
    profiles:
      - dev
      - prod
    networks:
      - parrot-network
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    profiles:
      - dev
      - prod
    networks:
      - parrot-network

  test:
    build:
      context: .
      target: test
    environment:
      - DATABASE_URL=sqlite:///db.sqlite
      - USER_MANAGER_SECRET=test-secret
      - AWS_ACCESS_KEY_ID=test-key
      - AWS_SECRET_ACCESS_KEY=test-secret-key
      - AWS_REGION=test-region
      - BUCKET_NAME=test-bucket
      - MODEL_API_URL=http://test-model-api.com
      - ADMIN_USERNAME=foobarbaz
      - ADMIN_PASSWORD_HASH=foobarbaz
    profiles:
      - test
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:

networks:
  parrot-network:
    name: parrot-network
    external: true
