services:
  web:
    image: euanoturner/pronunciation-app:${IMAGE_TAG}
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - USER_MANAGER_SECRET=${USER_MANAGER_SECRET}
      - MODEL_API_URL=${MODEL_API_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
      - ROLLBAR_ENVIRONMENT=${ROLLBAR_ENVIRONMENT}
      - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
    depends_on:
      - db
      - redis
    restart: unless-stopped
    profiles:
      - dev
      - prod
    networks:
      - default
      - parrot-network
  
  cron:
    image: euanoturner/pronunciation-app:${IMAGE_TAG}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
      - redis
    restart: unless-stopped
    profiles:
      - dev
      - prod

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    profiles:
      - dev
      - prod

  test:
    build:
      context: .
      target: test
    environment:
      - DATABASE_URL=sqlite:///db.sqlite
      - USER_MANAGER_SECRET=test-secret
      - AWS_ACCESS_KEY_ID=test-key
      - AWS_SECRET_ACCESS_KEY=test-secret-key
      - AWS_REGION=test-region
      - BUCKET_NAME=test-bucket
      - MODEL_API_URL=http://test-model-api.com
      - ADMIN_USERNAME=foobarbaz
      - ADMIN_PASSWORD_HASH=foobarbaz
      - ROLLBAR_ENVIRONMENT=testing
      - ROLLBAR_ACCESS_TOKEN=""
    profiles:
      - test
    networks:
      - default
    depends_on:
      - redis
  
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    profiles:
      - dev
      - prod
      - test

volumes:
  postgres_data:
  redis_data:

networks:
  parrot-network:
    name: parrot-network
    external: true
