services:
  web:
    image: euanoturner/pronunciation-app:${IMAGE_TAG}
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - USER_MANAGER_SECRET=${USER_MANAGER_SECRET}
    depends_on:
      - db
    restart: unless-stopped
    profiles:
      - dev
      - prod
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    profiles:
      - dev
      - prod

  test:
    build:
      context: .
      target: test
    environment:
      - DATABASE_URL=sqlite:///db.sqlite
      - USER_MANAGER_SECRET=test-secret
      - AWS_ACCESS_KEY_ID=test-key
      - AWS_SECRET_ACCESS_KEY=test-secret-key
      - AWS_REGION=test-region
      - BUCKET_NAME=test-bucket
    profiles:
      - test

volumes:
  postgres_data: