name: Continuous Integration

on:
  push:
    branches:
      -  '*'
  pull_request:
    branches:
      -  '*'

jobs:
  test:
    name: Run Tests

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run checks
      run: pre-commit run --all-files

    - name: Build and run tests
      run: docker compose --profile test up --build --abort-on-container-exit
