name: Continuous Integration

on:
  push:
    branches:
      -  '*'
  pull_request:
    branches:
      -  '*'

jobs:
  test:
    name: Run Tests

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Build and run tests
      run: docker compose --profile test up --build --abort-on-container-exit
