name: CI/CD Pipeline for Python API

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest  
        
  deploy:
    needs: build-and-test
    runs-on: ubuntu-20.04
    if: ${{ success() }}
  
    steps:
    - name: Copy files to server
      run: |
        scp -r ./* ts1622@cloud-vm-41-85.doc.ic.ac.uk:/usr/code
  
    - name: Restart API service
      run: |
        ssh ts1622@cloud-vm-41-85.doc.ic.ac.uk 'sudo systemctl restart flask_app.service'
